version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bookshelf_idp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net
    ports:
      - "5433:5432"
    deploy:
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookshelf.ro
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db-net
    depends_on:
      - postgres
    deploy:
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  database-service:
    image: adacosma/database-service:latest
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
    networks:
      - backend-net
      - db-net
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8083 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  auth-service:
    image: adacosma/auth-service:latest
    environment:
      DATABASE_SERVICE_URL: http://database-service:8083
    networks:
      - backend-net
    depends_on:
      - database-service
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  library-service:
    image: adacosma/library-service:latest
    environment:
      DATABASE_SERVICE_URL: http://database-service:8083
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
    networks:
      - backend-net
    depends_on:
      - database-service
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  notification-service:
    image: adacosma/notification-service:latest
    environment:
      DATABASE_SERVICE_URL: http://database-service:8083
    networks:
      - backend-net
    depends_on:
      - database-service
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    configs:
      - source: kong_config
        target: /usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - frontend-net
      - backend-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  react-frontend:
    image: adacosma/react-frontend:latest
    ports:
      - "5173:80"
    networks:
      - frontend-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker-2]
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitoring-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitoring-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

configs:
  kong_config:
    file: ./kong/kong.yml

volumes:
  postgres_data:
  portainer_data:
  prometheus_data:
  grafana_data:

networks:
  frontend-net:
    driver: overlay
    attachable: true
  backend-net:
    driver: overlay
    attachable: true
  db-net:
    driver: overlay
    attachable: true
  monitoring-net:
    driver: overlay
    attachable: true
